version: '3'

services:
  mysql-main:
    container_name: nest-auth
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=inventory-management
    volumes:
      - db-data:/var/lib/mysql:cached

volumes:
  db-data:
