version: '3.9'

services:
  db-main:
    container_name: nest-auth
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgres

volumes:
  db-data:
